name: test call workflow

run-name: "Deploy Core IaC with config '${{ inputs.config }}' "

on:
  workflow_dispatch:
    inputs:
      config:
        required: true
        type: string
        default: "gbordier"



jobs:
  get_config:
    name: Load Guardian Core IaC configuration
    uses: ./.github/workflows/load-config.yml
    with:
      config: ${{ inputs.config }}

  deploy_iac:
    name: "calling job"
    needs: get_config

    - name: "read subworkflow variable"
      id: deploy
      run:|
       echo "subworkflow variable resource group id is  ${{ needs.get_config.outputs.resource_group_name }}"
